server:
  port: 8086
spring:
  application:
    name: save-service
  datasource:
    url: jdbc:postgresql://localhost:5432/innowise
    username: postgres
    password: 123414
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-interval: 20s
        health-check-timeout: 6s
      config:
        enabled: false
