version: '3.1'
services:
  dbpostgresql:
    container_name: postgres
    image: postgres

    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - mynetwork

  app:
    container_name: springboot-app
    image: calculator
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge