spring:
  application:
    name: mult-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-interval: 20s
        health-check-timeout: 6s
  config:
    import: "consul:"
server:
  port: 8084